const SERVER_IP = "localhost:3997";

export const ENV = {
    BASE_PATH: `http://${SERVER_IP}/API/v1`,
    API_ROUTES: {
        nvQNHOaD1pGaVnr6MEpaeRsYAxiH8kM4L0: "/auth/login",
        XlZaTHhsYYDR7eUpe6Ock0YR3NApcri6EOjxDhJbtWVIC6nG4eCU1: "/usuario/crear/individual",
        NFOflvkVgbgyooWKYxGmXPfJTwu5gXhRMeIqGJCvgfAWevs2MQzCLU: "/usuario/crear/lista",
        YVCzWobTmjwdBLxpnvZDCN50xuLa5EU: "/usuario/eliminar",
        G22HHEoHdp2J1jF4JShU8w8ixWpbs6g7Ft1ViZbuvPoNNl23dAU: "/usuario/actualizar",
        aQB4BaS1i3puGyzLQdK79kupg3aShSpIOU: "/usuario/buscar/usuario",
        xtbiFDl0Crb6x42BFu3xEKBfLNuQKhNByemD1bc7g4njmMbshQOC: "/usuario/buscar/consultor",
        L4bGEcZxAnjetUarpJVSCVOexDA4I8MYQwlLiL6CXUZzzh3zsIMaOAA: "/usuario/buscar/administradorapoyo",
        sCut6QZaJ71RgMR6pGjAKJ5iO304nvJXi80IMrUWnsHw0ASzyqOA: "/usuario/buscar/administrador",
        kPBnDqc5yVlf0Hs7cjzhJ8vA9OZwjjxnZydqwJQceEGuvp59ONOUU: "/usuario/buscar/matricula",
        R0WYKoBdXJ0gzqFI3Gtrr8R82NDNluRqBg62NzSqJvTrTyqjbe22UOGI: "/grupo/crear/individual",
        N1Pd4tsPNNhd0duhg2MBNDBbER22oJHQAG: "/usuario/agregargrupo",
        v3ejHiMk2lSFjdorSLLe0Db7X9iiyB4QG: "/usuario/quitargrupo",
        BKn8x4vGsHimj8qRwDZj36nmW4scIAAsRC: "/usuario/correo/reenviar",
        EOPBPoSLej9LC1xm6H6sW82FnISfU6FPVe5bAjIgFJYSRwXMDDuCLG: "/grupo/crear/lista",
        x4A4MEAoshYSoAmMja4Sseaj6lqrJMYEG: "/grupo/eliminar",
        z78NzUW6bIKfYMjinAQAfZCMVg5pGUAG: "/grupo/activar",
        mOS33VY9GmuLpbDX60m94udBXRGZbRGsDG: "/grupo/desactivar",
        gl5C3lRNO66rhil5MeCnDFD8WLMIOG: "/grupo/buscar",
        qQANNmoaeTiGByckDsi5mGIqqHU33gGA: "/grupo/buscar/activos",
        OoPr5tGbQ4UbxfsgpzYtWLX0FTHImUEG: "/grupo/editar",
        cRaXoJXJBEMdhYvVCe75aWMeza5TcbwCF: "/fecha/crear",
        QqKu8VqZBGbet6PBK5xv4DPosMAskKyEOF: "/fecha/buscar",
        idfg8SRgSCyRAAYLi5aFtzhLw0Tl1hQEF: "/fecha/eliminar",
        MrCGGgYbz7bGyIIOxC5QxaeomHx2pOADlTWt4WMwQdO1UMd5iHCAI: "/asistencia/crear/individual",
        LvPC6YcWZOZ7tcfI4Jm3Vc7bbkwqsOROzgla21fVBhXvcZXQZdaECLA: "/asistencia/crear/lista",
        X68nbSAEMV6KkoeQkkwayOn7aA4OzE2T0hLyCqOxsZHcgxEPwtEA: "/asistencia/eliminar",
        PuEkEqdgECgyKaFyquPDFhpuVkDMYFIyx0nHCnpmzCBV9NMeZOA: "/asistencia/buscar",
        NmubWWi2BC2gcFxB5RVIs19jyRmr9mnEu5JFwkzfYGQtETGQ5vlGaPAP: "/asistencia/buscar/porcentaje/plantel",
        AOF4v3huqCB2PLdHoenhyoBYr0gshR0cVMYp6Hxva4Uzp7VA3LkLaibuhlfjwDJNhRv0fpOcNwPAC: "/asistencia/buscar/porcentaje/cuatrimestre",
        Z5pmoaUSeuZD6ARgshQZbcWoUVEhdaEZETkplurq5pDKkDI5N6jPACA: "/asistencia/buscar/porcentaje/carrera",
        ovuhvdfcaQKBemSca10h1niFA7cjpqXAGbEY1cMaNPvPKiWmzAuPAT: "/asistencia/buscar/porcentaje/turno",
        NLlwlUWIy2l3hDmAYvKTaHHaDwuvviWlYvzOLlGOkpByhADt17kPAG: "/asistencia/buscar/porcentaje/grupo",
        xW7RTiz5aMgFSYOWMNXJ0NwyZH1EeU944IHll5kE7qn05NSTbigPAA: "/asistencia/buscar/porcentaje/alumno",
        cnlQltoV3Un6QqfHutnWJoVUYyHe4OBXLBahwbBdbsiTookIPUCAI: "/alumno/crear/individual",
        JRftGUGV34Ke1dlVMa2PIOk1tVu7quMgkD7gcP88PUR16qL2CUCRLA: "/alumno/crear/lista",
        S75wCLxy6ZkpSHYjJRgN8qdnBrQkH2EBA: "/alumno/eliminar",
        XOoFVA5ed0IKBo5xxRubQl9zzU0MNjm7kgXGek1Do8ZtDYoS3kAA: "/alumno/actualizar",
        rP2cqUJM5x56b5bbkrOiyxbN6woiXAOAS: "/alumno/todos",
        fDxXEaGSGUfF0xIl4ybxMk2uS9PwtzVdTN4tP7JX8oLBnOeaOUA: "/alumno/matricula",
        wgJgf1yyn1D3yYNQ0Z802IAdy517MosAP: "/alertas/plantel",
        obtenerEncoding: "/api/encoding/",
    }
}